
export const mydata = {
   "ALCOHOLS":
        ["ETHANOL ALL GRADES", "BENZYL ALCOHOL", "ISO PROPYL ALCOHOL  (IPA)", "METHANOL", "METHYLENE CHLORIDE", "MONO ETHYLENE GLYCOL", "MONOPROPYLENE GLYCOL (MPG)", "N - BUTANOL", "TEXANOL"],
    "ESTERS":
        ["ETHYL ACETATE", "ISO BUTYL ACETATE", "ISO PROPYL ACETATE", "N BUTYL", "N PROPYL ACETATE"],
    "GLYCOL ETHERS / ESTERS":
        ["BUTYL GLYCOL", "ETHYL GLYCOL", "METHOXY PROPANOL", "METHOXY PROPYL ACETATE"], 
    "HYDROCARBONS":
        ["SOLVENT NAPHTHA - 100", "TOLUENE", "WHITESPIRIT", "XYLENE"],
    "KETONES":
        ["ACETONE","CYCLOHEXANONE"],
    "PIGMENTS": 
        ["BLACK 4330 SYNOX", "BROWN 4610 SYNOX", "BROWN 663 DRAGON", "GREEN 4590", "POLYETHYLENE GLYCOL 400", "RED 4130", "RED 4222", "YELLOW BAYER", "YELLOW 4920 SYNOX"],
    "PRESERVATIVES": ["BIOCIDE"],
    "PLASTICIZERS":
        [ "DBP , DIBUTYL PHTHALATE", "DOP, DIOCTYL PHTHALATE" ],
    "TITANIUM":
        ["TITAN 121- CRYSTAL", "TITAN 128", "TITAN 902", "TITAN CHIKI", "TITAN CHINESE 298", "TITAN 134", "TITAN 706", "TITAN LEMON"],
    "THICKENERS": 
        ["AEROSIL200", "BERMOCOLL EBS 481 FQ"], 
    "INORGANIC BASES":
        ["AMMONIA", "CAUSTIC SODA FLAKES", "KOH, POTASSIUM HYDROXIDE", "SODIUM HYDROGEN CARBONATE (SODIUM BICARBONATE)"],
    "METALLIC COMPOUNDS": 
        ["ALUMINIUM PASTE LEAFING", "ZINC DUST", "ZINC OXIDE LITHOPONE","ZINC STEARATE"],
    "SPECIALITY CHEMICALS":
        ["ANTI FOAM", "ICOLLEEN ICEBERG", "KAOLIN", "TEXAPON"],
    "POLYMERIC COMPOUNDS":
        ["STYRENE ACRYLIC", "CARBOPOL", "POLYETHYLENE GLYCOL 400"],
    "OTHER CHEMICALS":
        ["ALUMINIUM SILICATE", "CALCIUM CARBONATE", "CARBOPOL", "CARBON BLACK 660", "CARBON BLACK UCM", "CITRIC ACID", "GLYCERIN", "DLP", "DMF", "LIGHT LIQUID PARAFFIN BP", "SODIUM HEXA MATA PHOSPHATE", "SOYALECITHINE", "STEARIC ACID", "TALC", "ZINC PHOSPHATE",]
}